name: CI-MLflow-Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ============================
    # CHECKOUT PROJECT
    # ============================
    - name: Checkout repository
      uses: actions/checkout@v3

    # ============================
    # PYTHON ENV
    # ============================
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 dagshub==0.3.15
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    # ============================
    # RUN MLFLOW
    # ============================
    - name: Run MLflow Project
      run: |
        mlflow run . --env-manager=local

    # ============================
    # GET LATEST RUN_ID
    # ============================
    - name: Get latest run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest run_id: $RUN_ID"

    # ============================
    # UPLOAD TO GOOGLE DRIVE
    # ============================
    - name: Upload run to Google Drive
      env:
        GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
      run: |
        python upload_to_gdrive.py

    # ============================
    # DOCKER BUILD (MLFLOW MODEL)
    # ============================
    - name: Build Docker Image
      run: |
        mlflow models build-docker \
          --model-uri "runs:/$RUN_ID/model" \
          --name "cc"

    # ============================
    # DOCKER HUB LOGIN
    # ============================
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # ============================
    # TAG & PUSH IMAGE
    # ============================
    - name: Push Docker Image
      run: |
        docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
