name: CI MLflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python
      - name: Set Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Cek env
      - name: Check ENV
        run: |
          echo "CSV_URL = $CSV_URL"

      # Install MLflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 dagshub==0.3.15

      # Jalankan MLflow project
      - name: Run MLflow
        run: |
          mlflow run . --env-manager=local

      # Ambil latest run_id
      - name: Get latest run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest RUN ID = $RUN_ID"

      # Install library Google Drive
      - name: Install Google Drive libs
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      # Upload ke Google Drive
      - name: Upload to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python MLproject/upload_to_gdrive.py

      # Build Docker model dari MLflow
      - name: Build Docker MLflow Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name cc

      # Login Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag Docker image
      - name: Tag Docker image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
