name: CI/CD Pipeline - Arini Final

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install mlflow==3.7.0
        pip install -r MLProject/requirements.txt

    # ================================
    # Run MLflow Project
    # ================================
    - name: Run MLflow Project
      run: |
        mlflow run MLProject \
          --env-manager=local \
          --experiment-name "Churn-CI-Training"

    # ================================
    # Upload MLflow Artifact (Skilled)
    # ================================
    - name: Upload MLruns Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlruns-artifacts
        path: MLProject/mlruns/

    # ================================
    # Get latest MLflow run_id
    # ================================
    - name: Get latest run_id
      id: get-run-id
      run: |
        RUN_ID=$(ls -t MLProject/mlruns/0 | head -n 1)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest Run ID: $RUN_ID"

    # ================================
    # Login Docker Hub
    # ================================
    - name: DockerHub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ================================
    # Build Docker Image From MLflow Model
    # ================================
    - name: Build Docker Image
      run: |
        mlflow models build-docker \
          --model-uri "MLProject/mlruns/0/${{ env.RUN_ID }}/artifacts/model" \
          --name "churn-ci-model" \
          --enable-mlserver

    # ================================
    # Tag Docker Image
    # ================================
    - name: Tag Docker Image
      run: |
        docker tag churn-ci-model:latest \
          ${{ secrets.DOCKER_USERNAME }}/churn-ci:latest

    # ================================
    # Push Docker Image to Docker Hub
    # ================================
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/churn-ci:latest
